module.exports = {
  Tech: "tech",
  Mgmt: "Management",
  Unknown: "Unknown",
  AcceptedReview: "AR",
  RejectedReview: "RR",
  ExceptionReview: "ER",
  PendingReview: "PR",
  ReviewTypes: [
    this.AcceptedReview,
    this.RejectedReview,
    this.ExceptionReview,
    this.PendingReview,
  ],
  App: "App",
  Web: "Web",
  Ml: "ML",
  Elec: "Electronics",
  CSec: "CyberSecurity",
  Game: "GameDev",
  TechDomains: [this.App, this.Web, this.Ml, this.Elec, this.CSec, this.Game],
  GDes: "GraphicDesign",
  Ui: "UI/UX",
  Vfx: "VFX",
  DesignDomains: [this.GDes, this.Ui, this.Vfx],
  MgmtDomains: [this.Mgmt],
};
